#!/usr/bin/env node

/**
 * Prisma Schema Composer
 * Combines all modular schema files from /prisma/schemas/ into a single schema.prisma
 * 
 * Usage: node build-schema.js
 */

const fs = require('fs');
const path = require('path');

const SCHEMAS_DIR = path.join(__dirname, 'schemas');
const OUTPUT_FILE = path.join(__dirname, 'schema.prisma');

console.log('🔨 Prisma Schema Composer');
console.log('='.repeat(50));

// Get all schema files in order
const schemaFiles = fs.readdirSync(SCHEMAS_DIR)
  .filter(f => f.endsWith('.prisma'))
  .sort();

console.log(`\n📂 Found ${schemaFiles.length} schema files:`);
schemaFiles.forEach((file, idx) => {
  console.log(`  ${idx + 1}. ${file}`);
});

// Read all schema content
console.log('\n📖 Reading schema files...');
const schemaContents = [];

for (const file of schemaFiles) {
  const filePath = path.join(SCHEMAS_DIR, file);
  let content = fs.readFileSync(filePath, 'utf-8');
  
  // Remove comments and empty lines at the top
  content = content
    .split('\n')
    .filter(line => !line.trim().startsWith('//'))
    .filter(line => line.trim().length > 0)
    .join('\n');
  
  schemaContents.push(content);
  console.log(`  ✓ ${file}`);
}

// Create the combined schema
const prismaHeader = `// ============================================================
// VYOMTECH ERP - COMPLETE PRISMA SCHEMA
// ============================================================
// This file is auto-generated by build-schema.js
// Do NOT edit manually - modify the modular schemas in /prisma/schemas/

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

// ============================================================
// MODULAR SCHEMAS COMBINED
// ============================================================

`;

const combinedSchema = prismaHeader + schemaContents.join('\n\n');

// Write the combined schema
console.log('\n✍️  Writing combined schema...');
fs.writeFileSync(OUTPUT_FILE, combinedSchema);
console.log(`  ✓ Created ${OUTPUT_FILE}`);

// Count models and tables
const modelMatches = combinedSchema.match(/^\s*model\s+\w+\s*\{/gm) || [];
console.log('\n📊 Schema Statistics:');
console.log(`  Total Models: ${modelMatches.length}`);
console.log(`  File Size: ${(combinedSchema.length / 1024).toFixed(2)} KB`);

console.log('\n✨ Done!');
console.log('\nNext steps:');
console.log('  1. Run: npx prisma validate');
console.log('  2. Run: npx prisma migrate dev --name "add_all_tables"');
console.log('  3. Run: npx prisma generate');
